language: node_js
node_js: node
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 121.43.224.240
install:
# - npm install
  - echo install
script:
# - npm run build
  - echo script
before_deploy: 
  - echo before_deploy
  - openssl aes-256-cbc -K $encrypted_d28f6dc8aef7_key -iv $encrypted_d28f6dc8aef7_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  # 开启 ssh-agent，即允许使用 ssh 命令
  - eval "$(ssh-agent -s)"
  # 给予 id_rsa 文件权限，避免警告
  - chmod 600 ~/.ssh/id_rsa
  # 将私钥添加到 ssh
  - ssh-add ~/.ssh/id_rsa
deploy:
  - ssh root@121.43.224.240 "ls"

