language: node_js
node_js: node
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts: 121.43.224.240
before_install:
  - openssl aes-256-cbc -K $encrypted_d28f6dc8aef7_key -iv $encrypted_d28f6dc8aef7_iv -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
  # 给予 id_rsa 文件权限，避免警告
  - chmod 600 ~/.ssh/id_rsa
  - chmod 700 .travis/deploy.sh
install: 
  - npm install
script:
  - npm run build
after_success:
  - .travis/deploy.sh
  - echo "deploy success"

